=== jcheron/kobject/controller/controller.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="controllers" type="controllerType"></xsd:element>
    <xsd:complexType name="classType">
    	<xsd:sequence>
    		<xsd:element name="member" type="memberType" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="name" type="xsd:string"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="memberType">
    	<xsd:attribute name="name" type="xsd:string"></xsd:attribute>
    	<xsd:attribute name="required" type="xsd:boolean"></xsd:attribute>
    	<xsd:attribute name="min" type="xsd:int"></xsd:attribute>
    	<xsd:attribute name="max" type="xsd:int"></xsd:attribute>
    	<xsd:attribute name="type" type="tType"></xsd:attribute>
    	<xsd:attribute name="control" type="cType"></xsd:attribute>
    	<xsd:attribute name="regExpr" type="xsd:string"></xsd:attribute>
    	<xsd:attribute name="list" type="xsd:string"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="controllerType">
    	<xsd:sequence>
    		<xsd:element name="class" type="classType" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="tType">
    	<xsd:restriction base="xsd:string">
    		<xsd:enumeration value="autoinc"></xsd:enumeration>
    		<xsd:enumeration value="num"></xsd:enumeration>
    		<xsd:enumeration value="string"></xsd:enumeration>
    		<xsd:enumeration value="integer"></xsd:enumeration>
    		<xsd:enumeration value="boolean"></xsd:enumeration>
    		<xsd:enumeration value="date"></xsd:enumeration>
    		<xsd:enumeration value="time"></xsd:enumeration>
    		<xsd:enumeration value="datetime"></xsd:enumeration>
    		<xsd:enumeration value="tel"></xsd:enumeration>
    		<xsd:enumeration value="mail"></xsd:enumeration>
    	</xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="cType">
    	<xsd:restriction base="xsd:string">
    		<xsd:enumeration value="text"></xsd:enumeration>
    		<xsd:enumeration value="hidden"></xsd:enumeration>
    		<xsd:enumeration value="cmb"></xsd:enumeration>
    		<xsd:enumeration value="list"></xsd:enumeration>
    		<xsd:enumeration value="radio"></xsd:enumeration>
    		<xsd:enumeration value="checkbox"></xsd:enumeration>
    		<xsd:enumeration value="date"></xsd:enumeration>
    		<xsd:enumeration value="file"></xsd:enumeration>
    		<xsd:enumeration value="image"></xsd:enumeration>
    		<xsd:enumeration value="textarea"></xsd:enumeration>
    		<xsd:enumeration value="password"></xsd:enumeration>
    		<xsd:enumeration value="label"></xsd:enumeration>
    	</xsd:restriction>
    </xsd:simpleType>    
</xsd:schema>

=== jcheron/kobject/src/kobject.xml
<?xml version="1.0" encoding="UTF-8"?>
<controllers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:noNamespaceSchemaLocation="http://api.kobject.net/xml/controller.xsd">
	<class name="KAbsence">
		<member name="idEtudiant" required="1" max="11" type="integer" />
		<member name="idSeance" required="1" max="11" type="integer" />
		<member name="heures" max="15" type="string" />
		<member name="DateA" required="1" type="date" />
	</class>
	<class name="KClasse">
		<member name="id" max="11" type="autoinc" />
		<member name="nom" max="20" type="string" />
	</class>
	<class name="KCours">
		<member name="id" max="11" type="autoinc" />
		<member name="idMatiere" required="1" max="11" type="integer" />
		<member name="idEnseignant" required="1" max="11" type="integer" />
	</class>
	<class name="KEnseignant">
		<member name="id" max="11" type="autoinc" />
		<member name="nom" max="40" type="string" />
		<member name="prenom" max="20" type="string" />
	</class>
	<class name="KEtudiant">
		<member name="id" max="11" type="autoinc" />
		<member name="idClasse" required="1" max="11" type="integer" />
		<member name="nom" max="40" type="string" />
		<member name="prenom" max="20" type="string" />
	</class>
	<class name="KHeure">
		<member name="heure" required="1" type="time" />
	</class>
	<class name="KJoursemaine">
		<member name="jour" required="1" max="10" type="string" />
	</class>
	<class name="KMatiere">
		<member name="id" max="11" type="autoinc" />
		<member name="nom" max="30" type="string" />
	</class>
	<class name="KSeance">
		<member name="id" max="11" type="autoinc" />
		<member name="idClasse" required="1" max="11" type="integer" />
		<member name="idCours" required="1" max="11" type="integer" />
		<member name="duree" max="30" min="18" type="integer" />
		<member name="heure" type="time" />
		<member name="jour" list="{Lundi,Mardi,Mercredi,Jeudi,Vendredi}" />
	</class>
</controllers>
